### ISSUE TITLE
Relationships not being retrieved by get method despite relationships parameter

### ISSUE THREAD

**Issue by AcostaLm** [rmitesh/laravel-pantry#6]
In the documentation, the `get` method indicates that it receives a `relationships` parameter to add to the query. However, currently, the relationships are not being retrieved.

For example:
```php
$room = $roomPantry->get(
            $id,
            ['*'],
            ['with' => ['type']]
        );
        dd($room);
```

The `dd` output shows an empty `relations` property.

![image](https://github.com/rmitesh/laravel-pantry/assets/16061673/bebdfd08-02c4-46a3-bb16-d1ee08b4abd8)

**Comment by rmitesh** [comment]
Issue resolved in #7
